import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useMoralis } from 'react-moralis';
import Header from '../components/header/Header';
import Login from '../components/login/Login';
import Tabs from '../components/tabs/Tabs';

export default function Home() {
  const { isAuthenticated } = useMoralis();
  const router = useRouter();
  if (!isAuthenticated) {
    return <Login />;
  }
  return (
    <div className="bg-body w-screen h-screen">
      <Head>
        <title>WEB3 DASHBOARD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Tabs/>
    </div>
  );
}
